ec2 instance construct
enfogroup/aws-cdk-compliance pull request #54
Opened 2022-11-11 02:30 UTC by kabo

2022-11-11 12:20 UTC, castodius commented on lib/ec2.ts
> +          // TODO: only approved AMIs ?
Turn these TODOs into issues instead

2022-11-11 12:21 UTC, castodius requested changes
Turn the TODOs into issues and I will approve

2023-02-28 21:26 UTC, kabo commented on lib/ec2.ts
> +          // TODO: only approved AMIs ?
Created #55 , #56 , and #57

2023-03-01 06:07 UTC, castodius approved these changes

2023-06-19 10:40 UTC, merged